# Generated by Django 3.1.7 on 2021-04-04 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('county', models.CharField(max_length=50)),
                ('person_details', models.CharField(max_length=1000)),
                ('awards', models.CharField(max_length=50)),
                ('award_nominations', models.CharField(max_length=50)),
                ('link', models.URLField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('county', models.CharField(max_length=50)),
                ('person_details', models.CharField(max_length=1000, null=True)),
                ('awards', models.CharField(max_length=50, null=True)),
                ('award_nominations', models.CharField(max_length=50, null=True)),
                ('link', models.URLField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movies_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('description', models.CharField(max_length=1000, null=True)),
                ('genres', models.CharField(max_length=50)),
                ('budget', models.IntegerField()),
                ('rating', models.FloatField(blank=True)),
                ('duration', models.IntegerField()),
                ('county', models.CharField(max_length=50)),
                ('likes', models.IntegerField(blank=True, default=0)),
                ('poster', models.URLField()),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ActedBy+', to='movies.actor')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='movies.director')),
            ],
        ),
    ]
