# Generated by Django 3.1.7 on 2021-04-21 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('county', models.CharField(max_length=50)),
                ('person_details', models.CharField(max_length=1000)),
                ('awards', models.CharField(max_length=50)),
                ('award_nominations', models.CharField(max_length=50)),
                ('link', models.URLField(max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Actor',
                'verbose_name_plural': 'Actors',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('county', models.CharField(max_length=50)),
                ('person_details', models.CharField(max_length=1000, null=True)),
                ('awards', models.CharField(max_length=50, null=True)),
                ('award_nominations', models.CharField(max_length=50, null=True)),
                ('link', models.URLField(max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directors',
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movies_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('description', models.CharField(max_length=1000, null=True)),
                ('budget', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True)),
                ('duration', models.IntegerField()),
                ('county', models.CharField(max_length=50)),
                ('likes', models.IntegerField(blank=True, default=0)),
                ('poster', models.URLField()),
                ('actors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.actor')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.director')),
                ('genres', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.genres')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
    ]
