# Generated by Django 3.1.7 on 2021-04-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='movies',
            name='genres',
        ),
        migrations.AddField(
            model_name='movies',
            name='genres',
            field=models.ManyToManyField(null=True, to='movies.Genres'),
        ),
    ]
