# Generated by Django 3.1.7 on 2021-04-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20210411_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='actor',
        ),
        migrations.AddField(
            model_name='movies',
            name='actor',
            field=models.ManyToManyField(blank=True, null=True, to='movies.Actor'),
        ),
    ]
