# Generated by Django 3.1.7 on 2021-04-11 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20210411_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='actor',
            new_name='actors',
        ),
    ]
