# Generated by Django 3.1.7 on 2021-04-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20210411_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='budget',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
