# Generated by Django 3.1.7 on 2021-04-12 12:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20210411_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='actors',
            field=models.ManyToManyField(blank=True, to='movies.Actor'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='director',
            field=models.ForeignKey(blank=True, default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='movies.director'),
            preserve_default=False,
        ),
    ]
